In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
# Provides probabilities through normalization
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [3]:
x = np.array([2.0, 1.0, 0.1])
outputs = softmax(x)
print(outputs)

[0.65900114 0.24243297 0.09856589]


In [4]:
x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim=0)
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [6]:
# Cross entropy loss gives us loss for softmax
# One hot encoded class labels -> softmax proabilities
def cross_entropy(actual, predicted):
    loss = -np.sum(actual * np.log(predicted))
    return loss

Y = np.array([1, 0, 0])
Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])
l_good = cross_entropy(Y, Y_pred_good)
l_bad = cross_entropy(Y, Y_pred_bad)
print(f'{l_good=:.4f}, {l_bad=:.4f}')

l_good=0.3567, l_bad=2.3026


In [10]:
# Pytorch automatically adds softmax for CrossEntropyLoss, Y should not be one-hot encoded, y_pred should be raw (no softmax)
loss = nn.CrossEntropyLoss()
Y = torch.tensor([2, 0, 1])
# nsamples x nclasses
Y_pred_good = torch.tensor([[0.1, 1.0, 2.1], [2.0, 1.0, 0.1], [0.1, 3.0, 0.1]])
Y_pred_bad = torch.tensor([[2.1, 2.0, 0.1], [0.1, 1.0, 2.1], [1.0, 3.0, 0.1]])

l_good = loss(Y_pred_good, Y)
l_bad = loss(Y_pred_bad, Y)

print(l_good.item())
print(l_bad.item())

_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)

print(predictions1)
print(predictions2)

0.3018244206905365
1.7571099996566772
tensor([2, 0, 1])
tensor([0, 2, 1])
